/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          orange: '#fb8626',
          dark: '#212121',
          gray: '#a4a4a4',
          light: '#ffffff',
          footer: '#505355',
        },
        orange: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        "outline": "#85736d",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#464747",
        "secondary-fixed-dim": "#c7c6c6",
        "secondary": "#5e5e5e",
        "surface": "#F8F9FA",
        "on-primary": "#ffffff",
        "on-secondary-container": "#1b1c1c",
        "secondary-fixed": "#e3e2e2",
        "inverse-on-surface": "#f4f0ef",
        "surface-variant": "#f4ded5",
        "surface-bright": "#fff8f6",
        "surface-tint": "#a63b00",
        "surface-container-highest": "#e5e2e1",
        "inverse-primary": "#ffb598",
        "surface-container": "#f0edec",
        "on-tertiary-container": "#001e2f",
        "on-surface": "#1d1b1a",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#322f2e",
        "surface-container-high": "#eae7e6",
        "on-primary-container": "#370e00",
        "background": "#F8F9FA",
        "on-primary-fixed": "#370e00",
        "outline-variant": "#d7c2b9",
        "tertiary": "#006492",
        "secondary-container": "#e3e2e2",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdbce",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed-dim": "#8aceff",
        "on-tertiary-fixed-variant": "#004b6f",
        "on-primary-fixed-variant": "#7f2b00",
        "on-surface-variant": "#52443d",
        "surface-container-low": "#f6f3f1",
        "tertiary-container": "#c9e6ff",
        "tertiary-fixed": "#c9e6ff",
        "on-background": "#1d1b1a",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#001e2f",
        "surface-dim": "#dedada",
        "primary": "#F16624",
        "on-error-container": "#410002",
        "primary-fixed-dim": "#ffb598",
        "on-tertiary": "#ffffff",
        "primary-container": "#F16624"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "epilogue": ["Epilogue", "sans-serif"],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
